### ISSUE TITLE
maxmemory not a number

### ISSUE THREAD

**Issue by ngmaclaren** [jkenlooper/puzzle-massive#69]
Setting up a local version of puzzle-massive on Ubuntu 16.04, ImageMagick 7.0.10-19, Python 3.7.2, apache2. After approving and rendering a puzzle I get "Failed to get puzzle pieces” when visiting that puzzle in the browser (Firefox 77.0.1) at local-puzzle-massive. Relevant output from log.sh is attached.

Thanks for your help!

![log-output-20200616](https://user-images.githubusercontent.com/45513933/84795016-f8bfed80-afc4-11ea-97cc-6018aa0e817c.png)

**Comment by jkenlooper** [comment]
I'm pretty sure this is caused by using an older Redis version that was installed on Ubuntu 16.  The code that gets the memory usage from Redis defaults to a None type instead of a number.  I'm guessing that there are other potential issues with using the older versions with the newer puzzle-massive codebase.  

For reference, the bin/setup.sh script sets the maxmemory to 500mb after installing redis-server on Ubuntu 20.04.
The redis command used to get maxmemory is the INFO command documented here: https://redis.io/commands/info

The maxmemory config is set to 500mb which was mostly arbitrary and should probably be made configurable.
